### ISSUE TITLE
Error: Determinant should be 1 but is 1.

### ISSUE THREAD

**Issue by dennisushi** [dfki-ric/pytransform3d#218]
```python
q = pyrot.quaternion_from_matrix(T_new[:3,:3].detach().numpy())
```
Leads to:
```bash
ValueError: Expected rotation matrix, but it failed the test for the determinant, which should be 1 but is 0.99999; that is, it probably represents a rotoreflection
```

So I added:
```pythob
T_new [:3,:3] = T_new[:3,:3]/torch.linalg.det(T_new[:3,:3])
q = pyrot.quaternion_from_matrix(T_new[:3,:3].detach().numpy())
```
And this ended up even more ridiculous:
```bash
ValueError: Expected rotation matrix, but it failed the test for the determinant, which should be 1 but is 1; that is, it probably represents a rotoreflection
```

**Comment by dennisushi** [comment]
```strict_check= False``` ignores the error, but it's weird that it happens in the first place.

**Comment by AlexanderFabisch** [comment]
Hi @dennisushi ,

thanks for reporting.

This is the check that fails:

https://github.com/dfki-ric/pytransform3d/blob/408a1e230de501e80232f933ad4ddffc241843cc/pytransform3d/rotations/_utils.py#L429-L437

Default value for tolerance is `1e-6`.

The error message obviously makes no sense, since reflection would mean that the determinant is -1.

However, a warning about numerical precision seems to make sense in that case. You can avoid it by orthonormalization before calling the function (`pytransform3d.rotations.norm_matrix`).

Could you tell me what your input is?

**Comment by dennisushi** [comment]
> Could you tell me what your input is?

The input was an optimal transform generated by SVD, in the end I solved it by converting to numpy before normalizing with the determinant instead of after. Thanks for the quick response.
